# Generated by Django 5.0.2 on 2025-05-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='function_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
